---
name: Pull Request or Push

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  call_central_workflow:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      deploy-docs: false
    permissions:
      contents: write
      id-token: write
      pages: write
      pull-requests: read
