---
name: Tests

on:
  workflow_call:

jobs:
  macOS:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os_version: [12, 13, 14, 15]

    runs-on: macos-${{ matrix.os_version }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
        with:
          fetch-depth: 2

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install 'nox[uv]>=2024.3'

      - name: Install Test Requirements
        run: |
          nox --force-color -e tests_all --install-only

      - name: Test
        env:
          SKIP_REQUIREMENTS_INSTALL: '1'
        run: |
          nox --force-color -e tests_all -- -vv --run-destructive

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-macos${{ matrix.os_version }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
        with:
          name: exitstatus-${{ github.job }}-macos${{ matrix.os_version }}
          path: exitstatus
          if-no-files-found: error
